version: "3"
services:
    # Kafka UI
    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        networks:
            - kafka
        ports:
            - 8080:8080
        depends_on:
            - kafka
            - zookeeper
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    # Kafka and zookeeper
    # Zookeeper
    zookeeper:
        restart: always
        container_name: zookeeper
        image: bitnami/zookeeper
        networks:
            - kafka
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"
        volumes:
            - zookeeper:/bitnami
    # Kafka
    kafka:
        restart: always
        depends_on:
            - zookeeper
        container_name: kafka
        image: bitnami/kafka
        networks:
            - kafka
        ports:
            - "9092:9092"
            - "9093:9093"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
            - KAFKA_AUTO_CREATE_TOPIC_ENABLE="false"
        volumes:
            - kafka:/bitnami
# Networks
networks:
    kafka:

        # Names our volume
volumes:
    zookeeper:
    kafka:
